alias mkd='mkdir'
alias rd='rm -r'
alias pingg='ping -c 3 www.google.com'
alias aerr='tail -f /var/log/apache2/error.log'
alias aacc='tail -f /var/log/apache2/access.log'
alias server='python -m SimpleHTTPServer'
alias e='$EDITOR'
alias yt='youtube-dl -t -f 18'
alias tmux='TERM=xterm-256color tmux -2'
alias x='xdg-open'
alias subl='$HOME/sublime/Sublime_Text_2/sublime_text' 
alias artisan='php artisan'
alias betty='$HOME/betty/main.rb'
alias app='sudo apt-get install'
alias ce='gvim -v'
alias g='git'
alias mp3='youtube-dl -f "bestaudio" -x -o "%(title)s.%(ext)s" --audio-format "mp3"'
alias nvim='VIMRUNTIME="$HOME/neovim/runtime" $HOME/neovim/build/bin/nvim'
alias nv='VIMRUNTIME="$HOME/neovim/runtime" $HOME/neovim/build/bin/nvim'
alias nvt='VIMRUNTIME="$HOME/neovim/runtime" $HOME/neovim/build/bin/nvim +terminal'
